nelmio_cors:
  defaults:
    origin_regex: true
    allow_origin: ['^http://localhost(:\d+)?$']
    allow_headers: ['Content-Type', 'Authorization']
    allow_methods: ['GET', 'POST', 'OPTIONS']
    max_age: 3600
  paths:
    '^/api/': ~
    '^/r/': ~
